Header     header
float64[]  joint_position
float64[]  joint_velocity
float64[]  joint_position_goal
float64[]  joint_velocity_goal
float64[]  joint_position_error
float64[]  joint_velocity_error

geometry_msgs/Pose             end_effector_frame

float64[] cartesian_position
float64[] cartesian_velocity
float64[] cartesian_position_goal
float64[] cartesian_velocity_goal
float64[] cartesian_position_error
float64[] cartesian_velocity_error
