set(_CATKIN_CURRENT_PACKAGE "plugin_msgs")
set(plugin_msgs_VERSION "0.0.0")
set(plugin_msgs_MAINTAINER "galen <galen@todo.todo>")
set(plugin_msgs_PACKAGE_FORMAT "1")
set(plugin_msgs_BUILD_DEPENDS "geometry_msgs" "message_generation" "roscpp" "std_msgs")
set(plugin_msgs_BUILD_EXPORT_DEPENDS "geometry_msgs" "roscpp" "std_msgs" "message_runtime")
set(plugin_msgs_BUILDTOOL_DEPENDS "catkin")
set(plugin_msgs_BUILDTOOL_EXPORT_DEPENDS )
set(plugin_msgs_EXEC_DEPENDS "geometry_msgs" "roscpp" "std_msgs" "message_runtime")
set(plugin_msgs_RUN_DEPENDS "geometry_msgs" "roscpp" "std_msgs" "message_runtime")
set(plugin_msgs_TEST_DEPENDS )
set(plugin_msgs_DOC_DEPENDS )
set(plugin_msgs_URL_WEBSITE "")
set(plugin_msgs_URL_BUGTRACKER "")
set(plugin_msgs_URL_REPOSITORY "")
set(plugin_msgs_DEPRECATED "")